repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.6.3
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        files: \.js|.jsx|.json|.css$
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.28.0
    hooks:
      - id: eslint
        files: \.jsx?$
        additional_dependencies:
          - eslint-plugin-simple-import-sort@7.0.0
          - eslint-plugin-prettier@3.4.0
          - eslint-plugin-unused-imports@1.1.1
