version: '3.7'

services:
  web:
    build: ./networthtracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./networthtracker/:/usr/src/networthtracker/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=some-password
      - POSTGRES_DB=net-worth-tracker

volumes:
  postgres_data: