version: "3.7"

services:
  # TODO: productionize, run locally for dev
  # ui:
  #   build: ./networthtracker-ui
  #   ports:
  #     - 3001:3001
  #   env_file:
  #     - ./networthtracker-ui/.env.dev
  #   volumes:
  #     - ./networthtracker-ui/public/:/usr/src/networthtracker-ui/public
  #     - ./networthtracker-ui/src/:/usr/src/networthtracker-ui/src

  web:
    build: ./networthtracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./networthtracker/:/usr/src/networthtracker/
    ports:
      - 8000:8000
    env_file:
      - ./networthtracker/.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=some-password
      - POSTGRES_DB=net-worth-tracker

volumes:
  postgres_data:
