# Generated by Django 3.1.7 on 2021-06-07 04:56

import uuid

import django.db.models.deletion
import networth.models.mixins.validate_owns_object
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Holding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("updated_on", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TickerSymbol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("price_per_unit", models.FloatField()),
                ("price_updated_on", models.DateTimeField()),
                ("symbol", models.CharField(max_length=20)),
                (
                    "exchange",
                    models.CharField(
                        choices=[
                            ("xtse", "Toronto Stock Exchange"),
                            ("xnys", "New York Stock Exchange"),
                            ("xnas", "Nasdaq"),
                            ("xlon", "London Stock Exchange"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("cad", "CAD"), ("usd", "USD")], max_length=3
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("equity", "Equity Security"),
                            ("debt", "Debt Security"),
                            ("hybrid", "Hybrid Security"),
                        ],
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "holding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.holding",
                    ),
                ),
                ("market_value", models.FloatField()),
                ("book_value", models.FloatField()),
                ("book_value_is_average", models.BooleanField(default=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("property", "Property"),
                            ("security", "Security"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("quantity", models.FloatField(default=1)),
            ],
            bases=(
                networth.models.mixins.validate_owns_object.ValidateOwnsObjectMixin,
                "networth.holding",
            ),
        ),
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "holding_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.holding",
                    ),
                ),
                ("amount_owing", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("mortgage", "Mortgage"),
                            ("loan", "Loan"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
            ],
            bases=(
                networth.models.mixins.validate_owns_object.ValidateOwnsObjectMixin,
                "networth.holding",
            ),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("transaction_date", models.DateTimeField()),
                ("settlement_date", models.DateTimeField()),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("buy", "Buy"),
                            ("sell", "Sell"),
                            ("deposit", "Deposit"),
                            ("withdraw", "Withdraw"),
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                        ],
                        max_length=8,
                    ),
                ),
                ("description", models.CharField(max_length=300, null=True)),
                ("quantity", models.FloatField(null=True)),
                ("gross_amount", models.FloatField()),
                ("net_amount", models.FloatField()),
                ("commission", models.FloatField(null=True)),
                ("updated_on", models.DateTimeField()),
                (
                    "holding",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networth.holding",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(
                networth.models.mixins.validate_owns_object.ValidateOwnsObjectMixin,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Cash",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.asset",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("cad", "CAD"), ("usd", "USD")], max_length=3
                    ),
                ),
            ],
            bases=("networth.asset",),
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.asset",
                    ),
                ),
                ("address", models.CharField(max_length=350)),
                ("special_notes", models.CharField(max_length=500)),
                ("purchased_on", models.DateTimeField(null=True)),
            ],
            bases=("networth.asset",),
        ),
        migrations.CreateModel(
            name="Security",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.asset",
                    ),
                ),
                ("exchange", models.CharField(max_length=50, null=True)),
                ("price_per_unit", models.FloatField()),
                (
                    "ticker_symbol",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="networth.tickersymbol",
                    ),
                ),
            ],
            bases=("networth.asset",),
        ),
    ]
