# Generated by Django 3.1.7 on 2021-03-25 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('market_value', models.FloatField()),
                ('book_value', models.FloatField()),
                ('book_value_is_average', models.BooleanField(default=True)),
                ('updated_on', models.DateTimeField()),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TickerSymbol',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('price_per_unit', models.FloatField()),
                ('price_updated_on', models.DateTimeField()),
                ('symbol', models.CharField(max_length=20)),
                ('exchange', models.CharField(
                    choices=[('xtse', 'Toronto Stock Exchange'), ('xnys', 'New York Stock Exchange'),
                             ('xnas', 'Nasdaq'), ('xlon', 'London Stock Exchange')], max_length=4)),
                ('currency', models.CharField(choices=[('cad', 'CAD'), ('usd', 'USD')], max_length=3)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(
                    choices=[('equity', 'Equity Security'), ('debt', 'Debt Security'), ('hybrid', 'Hybrid Security')],
                    max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField()),
                ('settlement_date', models.DateTimeField()),
                ('activity_type', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('gross_amount', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('commission', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('asset_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='networth.asset')),
                ('currency', models.CharField(choices=[('cad', 'CAD'), ('usd', 'USD')], max_length=3)),
            ],
            bases=('networth.asset',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('asset_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='networth.asset')),
                ('address', models.CharField(max_length=350)),
                ('special_notes', models.CharField(max_length=500)),
                ('purchased_on', models.DateTimeField(null=True)),
            ],
            bases=('networth.asset',),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('account_number', models.CharField(max_length=150)),
                ('type', models.CharField(max_length=150)),
                ('balance', models.FloatField()),
                (
                    'user_id',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('asset_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='networth.asset')),
                ('special_notes', models.CharField(max_length=500)),
                ('purchased_on', models.DateTimeField(null=True)),
                ('settlement_date', models.DateTimeField()),
                ('ticker_symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    to='networth.tickersymbol')),
            ],
            bases=('networth.asset',),
        ),
    ]
