# Generated by Django 3.1.7 on 2021-03-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0002_auto_20210325_0400")]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("property", "Property"),
                    ("security", "Security"),
                ],
                max_length=8,
                null=True,
            ),
        )
    ]
