# Generated by Django 3.1.7 on 2021-04-04 22:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0004_auto_20210329_0241")]

    operations = [
        migrations.AddField(
            model_name="account",
            name="updated_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="asset",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="networth.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="account",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="networth.account",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="networth.asset",
            ),
        ),
    ]
