# Generated by Django 3.1.7 on 2021-04-05 04:53

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0006_auto_20210405_0436")]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="updated_on",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 4, 5, 4, 53, 53, 756853)
            ),
            preserve_default=False,
        )
    ]
