# Generated by Django 3.1.7 on 2021-04-20 03:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("networth", "0007_transaction_updated_on")]

    operations = [
        migrations.RemoveField(model_name="asset", name="account"),
        migrations.RemoveField(model_name="transaction", name="account"),
        migrations.DeleteModel(name="Account"),
    ]
