# Generated by Django 3.1.7 on 2021-04-27 03:05

import uuid

import django.db.models.deletion
import networth.models.mixins.validate_owns_object
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("networth", "0008_auto_20210420_0347"),
    ]

    operations = [
        migrations.RemoveField(model_name="security", name="purchased_on"),
        migrations.RemoveField(model_name="security", name="settlement_date"),
        migrations.RemoveField(model_name="security", name="special_notes"),
        migrations.AddField(
            model_name="security",
            name="exchange",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="Liability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("description", models.CharField(max_length=500, null=True)),
                ("amount_owing", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("mortgage", "Mortgage"),
                            ("loan", "Loan"),
                        ],
                        max_length=11,
                        null=True,
                    ),
                ),
                ("updated_on", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(
                networth.models.mixins.validate_owns_object.ValidateOwnsObjectMixin,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="liability",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="networth.liability",
            ),
        ),
    ]
