# Generated by Django 3.1.7 on 2021-04-27 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0009_auto_20210427_0305")]

    operations = [
        migrations.RemoveField(model_name="transaction", name="asset"),
        migrations.RemoveField(model_name="transaction", name="liability"),
        migrations.CreateModel(
            name="LiabilityTransaction",
            fields=[
                (
                    "transaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.transaction",
                    ),
                ),
                (
                    "liability",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networth.liability",
                    ),
                ),
            ],
            bases=("networth.transaction",),
        ),
        migrations.CreateModel(
            name="AssetTransaction",
            fields=[
                (
                    "transaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="networth.transaction",
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="networth.asset",
                    ),
                ),
            ],
            bases=("networth.transaction",),
        ),
    ]
