# Generated by Django 3.1.7 on 2021-04-27 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0010_auto_20210427_0343")]

    operations = [
        migrations.RemoveField(
            model_name="liabilitytransaction", name="liability"
        ),
        migrations.RemoveField(
            model_name="liabilitytransaction", name="transaction_ptr"
        ),
        migrations.DeleteModel(name="AssetTransaction"),
        migrations.DeleteModel(name="LiabilityTransaction"),
        migrations.AddField(
            model_name="transaction",
            name="asset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="networth.asset",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="liability",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="networth.liability",
            ),
        ),
    ]
