# Generated by Django 3.1.7 on 2021-05-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0011_auto_20210427_0357")]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="price",
            new_name="price_per_unit",
        ),
        migrations.RemoveField(model_name="transaction", name="activity_type"),
        migrations.AddField(
            model_name="security",
            name="price_per_unit",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="security",
            name="quantity",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("buy", "Buy"),
                    ("sell", "Sell"),
                    ("deposit", "Deposit"),
                    ("withdraw", "Withdraw"),
                ],
                default="buy",
                max_length=8,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="commission",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.FloatField(null=True),
        ),
    ]
