# Generated by Django 3.1.7 on 2021-05-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("networth", "0012_auto_20210504_0444")]

    operations = [
        migrations.RemoveField(model_name="security", name="quantity"),
        migrations.RemoveField(
            model_name="transaction", name="price_per_unit"
        ),
        migrations.AddField(
            model_name="asset",
            name="quantity",
            field=models.FloatField(default=1),
        ),
    ]
